// src/pages/profile/MyProfilePage.tsx
//
// "Staffs Profile system — staff must be able to see their activities on
// their profile, see their bonuses and salaries."
//
// Info + activities are real, live data (prospects assigned, appointments
// created, deeds generated — filtered to the logged-in user via the real
// API where each entity actually tracks who did it; Customer has no such
// field on the backend, so it can't be included here). Photo and bonuses/
// salary are prototype-only — see src/mock/photos.ts and src/mock/payroll.ts.
// Bonuses are matched by full-name against the mock payroll store, which
// has no real userId link, so it's an approximate match, clearly flagged.
import React, { useMemo, useState } from 'react';
import { Alert, Button, Card, Col, Descriptions, Empty, Form, Input, List, Modal, Row, Space, Statistic, Table, Tag, Typography, message } from 'antd';
import {
  AuditOutlined, CalendarOutlined, EditOutlined, FileTextOutlined,
  IdcardOutlined, MailOutlined, PhoneOutlined, UserAddOutlined,
} from '@ant-design/icons';
import dayjs from 'dayjs';
import { useAuth } from '@/contexts/AuthContext';
import { PageHeader } from '@/components/shared/PageHeader';
import { PhotoUpload } from '@/components/shared/PhotoUpload';
import { roleLabels } from '@/constants/enums';
import { useUpdateUserMutation } from '@/api/users';
import { useProspectsQuery } from '@/api/prospects';
import { useAppointmentsQuery } from '@/api/appointments';
import { useDeedsQuery } from '@/api/deeds';
import { getAllBranchPayroll, type PayrollStatus } from '@/mock/payroll';

const { Title, Text } = Typography;

const payrollStatusColor: Record<PayrollStatus, string> = { pending: 'gold', processed: 'blue', paid: 'green' };

interface ActivityRow {
  key: string;
  type: 'Prospect' | 'Appointment' | 'Deed';
  title: string;
  detail: string;
  date: string;
}

export const MyProfilePage: React.FC = () => {
  const { user, hasRole, refreshUser } = useAuth();
  const [editModal, setEditModal] = useState(false);
  const [form] = Form.useForm();
  const updateUser = useUpdateUserMutation();

  const canSeeProspects = hasRole(['marketing_staff', 'marketing_director', 'admin']);
  const canSeeAppointments = hasRole(['customer_service', 'admin']);
  const canSeeDeeds = hasRole(['secretary', 'admin']);

  const { data: prospectsData, isLoading: prospectsLoading } = useProspectsQuery(
    { assignedUserId: user?.id, pageSize: 20 },
    canSeeProspects && !!user?.id
  );
  const { data: appointmentsData, isLoading: appointmentsLoading } = useAppointmentsQuery(
    { pageSize: 50 },
    canSeeAppointments
  );
  const { data: deedsData, isLoading: deedsLoading } = useDeedsQuery(
    { pageSize: 50 },
    canSeeDeeds
  );

  const activity: ActivityRow[] = useMemo(() => {
    const rows: ActivityRow[] = [];

    (prospectsData?.items ?? []).forEach((p) => {
      rows.push({
        key: `prospect-${p.id}`,
        type: 'Prospect',
        title: `${p.firstName} ${p.lastName}`,
        detail: `Assigned to you — ${p.status.replace('_', ' ')} (${p.source})`,
        date: p.updatedAt || p.createdAt,
      });
    });

    (appointmentsData?.items ?? [])
      .filter((a) => a.createdByUserId === user?.id)
      .forEach((a) => {
        rows.push({
          key: `appointment-${a.id}`,
          type: 'Appointment',
          title: `Appointment — ${dayjs(a.scheduledFor).format('MMM D, YYYY')}`,
          detail: `Created by you — ${a.status} (${a.source})`,
          date: a.updatedAt || a.createdAt,
        });
      });

    (deedsData?.items ?? [])
      .filter((d) => d.generatedByUserId === user?.id)
      .forEach((d) => {
        rows.push({
          key: `deed-${d.id}`,
          type: 'Deed',
          title: `Deed generated`,
          detail: `Deed #${d.id.slice(0, 8)} — generated by you`,
          date: d.createdAt,
        });
      });

    return rows.sort((a, b) => (a.date < b.date ? 1 : -1)).slice(0, 25);
  }, [prospectsData, appointmentsData, deedsData, user?.id]);

  const activityLoading = (canSeeProspects && prospectsLoading) || (canSeeAppointments && appointmentsLoading) || (canSeeDeeds && deedsLoading);
  const noActivitySourceAvailable = !canSeeProspects && !canSeeAppointments && !canSeeDeeds;

  const myPayroll = useMemo(() => {
    if (!user) return [];
    const fullName = `${user.firstName} ${user.lastName}`.trim().toLowerCase();
    return getAllBranchPayroll().filter((p) => p.staffName.trim().toLowerCase() === fullName);
  }, [user]);

  const totalBonusMinor = myPayroll.reduce((sum, p) => sum + p.bonusMinor, 0);
  const totalNetMinor = myPayroll.reduce((sum, p) => sum + p.netPayMinor, 0);

  const openEdit = () => {
    form.setFieldsValue({
      firstName: user?.firstName,
      lastName: user?.lastName,
      email: user?.email,
      phoneNumber: user?.phoneNumber,
    });
    setEditModal(true);
  };

  const handleSave = async (values: any) => {
    if (!user?.id) return;
    try {
      await updateUser.mutateAsync({ id: user.id, payload: values });
      await refreshUser();
      message.success('Profile updated');
      setEditModal(false);
    } catch (error: any) {
      message.error(error?.message || 'Failed to update profile');
    }
  };

  if (!user) return null;

  const payrollColumns = [
    { title: 'Code', dataIndex: 'code', key: 'code', render: (v: string) => <Tag>{v}</Tag> },
    { title: 'Month', dataIndex: 'month', key: 'month' },
    { title: 'Base Pay', key: 'base', render: (_: any, r: (typeof myPayroll)[number]) => `GHS ${(r.basePayMinor / 100).toLocaleString()}` },
    {
      title: 'Bonus',
      key: 'bonus',
      render: (_: any, r: (typeof myPayroll)[number]) => r.bonusMinor > 0
        ? <Tag color="green">GHS {(r.bonusMinor / 100).toLocaleString()}</Tag>
        : <span style={{ color: '#bbb' }}>—</span>,
    },
    { title: 'Net Pay', key: 'net', render: (_: any, r: (typeof myPayroll)[number]) => <strong>GHS {(r.netPayMinor / 100).toLocaleString()}</strong> },
    { title: 'Status', dataIndex: 'status', key: 'status', render: (v: PayrollStatus) => <Tag color={payrollStatusColor[v]}>{v}</Tag> },
  ];

  return (
    <div>
      <PageHeader title="My Profile" actions={[{ label: 'Edit Info', onClick: openEdit, icon: <EditOutlined /> }]} />

      <Card style={{ marginBottom: 24 }}>
        <Row gutter={24} align="middle">
          <Col>
            <PhotoUpload entityType="staff" entityId={user.id} size={80} />
          </Col>
          <Col flex="auto">
            <Title level={3} style={{ margin: 0 }}>{user.firstName} {user.lastName}</Title>
            <Space size={12} style={{ marginTop: 4 }}>
              <Tag color="blue">{roleLabels[user.role as keyof typeof roleLabels] || user.role}</Tag>
              <Text type="secondary" style={{ fontSize: 12 }}>Staff since {dayjs(user.createdAt).format('MMM YYYY')}</Text>
            </Space>
            <Descriptions column={{ xs: 1, sm: 2 }} style={{ marginTop: 16 }}>
              <Descriptions.Item label={<span><MailOutlined /> Email</span>}>{user.email}</Descriptions.Item>
              <Descriptions.Item label={<span><PhoneOutlined /> Phone</span>}>{user.phoneNumber}</Descriptions.Item>
            </Descriptions>
          </Col>
        </Row>
      </Card>

      <Card
        title={<span><AuditOutlined style={{ marginRight: 8 }} />My Activities</span>}
        style={{ marginBottom: 24 }}
      >
        {noActivitySourceAvailable ? (
          <Empty description="No trackable activity type exists for your role on the real API yet." />
        ) : activity.length > 0 ? (
          <List
            loading={activityLoading}
            dataSource={activity}
            renderItem={(row) => (
              <List.Item extra={<Text type="secondary" style={{ fontSize: 12 }}>{dayjs(row.date).format('MMM D, YYYY')}</Text>}>
                <List.Item.Meta
                  avatar={row.type === 'Prospect' ? <UserAddOutlined /> : row.type === 'Appointment' ? <CalendarOutlined /> : <FileTextOutlined />}
                  title={<span>{row.title} <Tag style={{ marginLeft: 8 }}>{row.type}</Tag></span>}
                  description={row.detail}
                />
              </List.Item>
            )}
          />
        ) : (
          <Empty description="No activity recorded for you yet." />
        )}
      </Card>

      <Card title={<span><IdcardOutlined style={{ marginRight: 8 }} />My Bonuses & Salary</span>}>
        <Alert
          type="warning"
          showIcon
          style={{ marginBottom: 16 }}
          message="Approximate match — preview only"
          description="Payroll records aren't linked to a real staff account yet, so these rows are matched by your full name against the mock payroll store. Confirm figures with Accounts before relying on them."
        />
        {myPayroll.length > 0 ? (
          <>
            <Row gutter={16} style={{ marginBottom: 16 }}>
              <Col xs={24} sm={12}>
                <Statistic title="Total Bonuses (sample)" value={totalBonusMinor / 100} prefix="GHS" precision={2} valueStyle={{ color: '#52c41a' }} />
              </Col>
              <Col xs={24} sm={12}>
                <Statistic title="Total Net Pay (sample)" value={totalNetMinor / 100} prefix="GHS" precision={2} />
              </Col>
            </Row>
            <Table columns={payrollColumns} dataSource={myPayroll} rowKey="id" pagination={false} size="small" />
          </>
        ) : (
          <Text type="secondary">No payroll records matched to your name yet.</Text>
        )}
      </Card>

      <Modal title="Edit Profile" open={editModal} onCancel={() => setEditModal(false)} footer={null} destroyOnClose>
        <Form form={form} layout="vertical" onFinish={handleSave}>
          <Form.Item name="firstName" label="First Name" rules={[{ required: true, message: 'Required' }]}>
            <Input />
          </Form.Item>
          <Form.Item name="lastName" label="Last Name" rules={[{ required: true, message: 'Required' }]}>
            <Input />
          </Form.Item>
          <Form.Item name="email" label="Email" rules={[{ required: true, type: 'email', message: 'Enter a valid email' }]}>
            <Input />
          </Form.Item>
          <Form.Item name="phoneNumber" label="Phone Number" rules={[{ required: true, message: 'Required' }]}>
            <Input />
          </Form.Item>
          <Form.Item>
            <Space>
              <Button type="primary" htmlType="submit" loading={updateUser.isPending}>Save</Button>
              <Button onClick={() => setEditModal(false)}>Cancel</Button>
            </Space>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};
